# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = "T", run = "plugin toggle-pane max-preview" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "M", run = "plugin mount" },
  { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
  { on = "i", run = 'plugin smart-enter' },
  { on = "<Enter>", run = 'plugin smart-enter' },
  { on = "S", run = 'shell "$SHELL" --block --confirm' },
  { on = [
    "'",
    "a",
  ], run = "plugin yamb --args=save", desc = "Add bookmark" },
  { on = [
    "'",
    "'",
  ], run = "plugin yamb --args=jump_by_fzf", desc = "Jump bookmark by fzf" },
  { on = [
    "'",
    "r",
  ], run = "plugin yamb --args=delete_by_key", desc = "Delete bookmark by key" },
  { on = [
    "P",
  ], run = "spot", desc = "Open spotter" },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  # Goto
  { on = [
    "g",
    "h",
  ], run = "cd C:/Users/pv/OneDrive/Desktop", desc = "Go home" },
  { on = [
    "g",
    "c",
  ], run = "cd %AppData%/yazi/config", desc = "Goto Yazi config dir" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Goto ~/Downloads" },
  { on = [
    "g",
    "<Space>",
  ], run = "cd --interactive", desc = "Jump interactively" },
  { on = [
    "g",
    "p",
  ], run = "cd D:/Rust_projects", desc = "Goto Rust_projects" },
  { on = [
    "g",
    "o",
  ], run = "cd D:/obsidian-repos/obsidian-for-gitee", desc = "Goto Obsidian Repos" },
  # { on = "-", run = "", desc = "Symlink the absolute path of yanked files" },
  # { on = "_", run = "PowerShell -Command \"$yanked = '%yanked%'; $relative = Resolve-Path $yanked -Relative; $link = Join-Path (Get-Location) (Split-Path $yanked -Leaf); if (Test-Path -Path $link) { Write-Host 'Link Existed' -ForegroundColor Red } else { cmd /c mklink $link $relative }\"", desc = "Symlink the relative path of yanked files" },
]
